In [1]:
import pandas as pd 
df=pd.read_csv("Sleep_health_and_lifestyle_dataset (1).csv")
df = df.dropna(subset=['Sleep Disorder']).copy()
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
! pip install pycaret

Requirement already satisfied: pycaret in .\.venv\Lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in .\.venv\Lib\site-packages (from pycaret) (9.9.0)
Requirement already satisfied: ipywidgets>=7.6.5 in .\.venv\Lib\site-packages (from pycaret) (8.1.8)
Requirement already satisfied: tqdm>=4.62.0 in .\.venv\Lib\site-packages (from pycaret) (4.67.2)
Requirement already satisfied: numpy<1.27,>=1.21 in .\.venv\Lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in .\.venv\Lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in .\.venv\Lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in .\.venv\Lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in .\.venv\Lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: scikit-learn>1.4.0 in .\.venv\Lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in .\.venv\Lib\site-packages (from pycaret) (2.0.6)
Requirement already satisfied: imbalanced-learn>=0.12.0 in .\.venv\Lib\site-packages (from pycaret) (0.14.1)
Requirement already satisfied: category-encoders>=2.4.0 in .\.venv\Lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in .\.venv\Lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in .\.venv\Lib\site-packages (from pycaret) (0.63.1)
Requirement already satisfied: requests>=2.27.1 in .\.venv\Lib\site-packages (from pycaret) (2.32.5)
Requirement already satisfied: psutil>=5.9.0 in .\.venv\Lib\site-packages (from pycaret) (7.2.2)
Requirement already satisfied: markupsafe>=2.0.1 in .\.venv\Lib\site-packages (from pycaret) (3.0.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in .\.venv\Lib\site-packages (from pycaret) (8.7.1)
Requirement already satisfied: nbformat>=4.2.0 in .\.venv\Lib\site-packages (from pycaret) (5.10.4)
Requirement already satisfied: cloudpickle in .\.venv\Lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in .\.venv\Lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in .\.venv\Lib\site-packages (from pycaret) (3.6.0)
Requirement already satisfied: matplotlib<3.8.0 in .\.venv\Lib\site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in .\.venv\Lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in .\.venv\Lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in .\.venv\Lib\site-packages (from pycaret) (6.5.2)
Requirement already satisfied: kaleido>=0.2.1 in .\.venv\Lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: schemdraw==0.15 in .\.venv\Lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in .\.venv\Lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in .\.venv\Lib\site-packages (from pycaret) (0.14.6)
Requirement already satisfied: sktime==0.26.0 in .\.venv\Lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in .\.venv\Lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in .\.venv\Lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from sktime==0.26.0->pycaret) (26.0)
Requirement already satisfied: scikit-base<0.8.0 in .\.venv\Lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (4.61.1)
Requirement already satisfied: kiwisolver>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.9)
Requirement already satisfied: pillow>=6.2.0 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (12.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\.venv\Lib\site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.venv\Lib\site-packages (from pandas<2.2.0->pycaret) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in .\.venv\Lib\site-packages (from pandas<2.2.0->pycaret) (2025.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in .\.venv\Lib\site-packages (from scikit-learn>1.4.0->pycaret) (3.6.0)
Requirement already satisfied: patsy>=0.5.1 in .\.venv\Lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in .\.venv\Lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.5)
Requirement already satisfied: zipp>=3.20 in .\.venv\Lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.23.0)
Requirement already satisfied: colorama>=0.4.4 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in .\.venv\Lib\site-packages (from ipython>=5.5.0->pycaret) (4.15.0)
Requirement already satisfied: wcwidth in .\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.5.3)
Requirement already satisfied: comm>=0.1.3 in .\.venv\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in .\.venv\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in .\.venv\Lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in .\.venv\Lib\site-packages (from jedi>=0.18.1->ipython>=5.5.0->pycaret) (0.8.5)
Requirement already satisfied: choreographer>=1.1.1 in .\.venv\Lib\site-packages (from kaleido>=0.2.1->pycaret) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in .\.venv\Lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in .\.venv\Lib\site-packages (from kaleido>=0.2.1->pycaret) (3.11.6)
Requirement already satisfied: pytest-timeout>=2.4.0 in .\.venv\Lib\site-packages (from kaleido>=0.2.1->pycaret) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in .\.venv\Lib\site-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret) (3.20.2)
Requirement already satisfied: fastjsonschema>=2.15 in .\.venv\Lib\site-packages (from nbformat>=4.2.0->pycaret) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in .\.venv\Lib\site-packages (from nbformat>=4.2.0->pycaret) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in .\.venv\Lib\site-packages (from nbformat>=4.2.0->pycaret) (5.9.1)
Requirement already satisfied: attrs>=22.2.0 in .\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in .\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (4.5.1)
Requirement already satisfied: llvmlite<0.47,>=0.46.0dev0 in .\.venv\Lib\site-packages (from numba>=0.55.0->pycaret) (0.46.0)
Requirement already satisfied: narwhals>=1.15.1 in .\.venv\Lib\site-packages (from plotly>=5.14.0->pycaret) (2.15.0)
Requirement already satisfied: dash>=2.11.0 in .\.venv\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.4.0)
Requirement already satisfied: tsdownsample>=0.1.3 in .\.venv\Lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in .\.venv\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in .\.venv\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.5)
Requirement already satisfied: retrying in .\.venv\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in .\.venv\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: setuptools in .\.venv\Lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (79.0.1)
Requirement already satisfied: blinker>=1.9.0 in .\.venv\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: click>=8.1.3 in .\.venv\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in .\.venv\Lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in .\.venv\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.4)
Requirement already satisfied: urllib3 in .\.venv\Lib\site-packages (from pmdarima>=2.0.4->pycaret) (2.6.3)
Requirement already satisfied: pytest>=7.0.0 in .\.venv\Lib\site-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (9.0.2)
Requirement already satisfied: iniconfig>=1.0.1 in .\.venv\Lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in .\.venv\Lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (1.6.0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests>=2.27.1->pycaret) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in .\.venv\Lib\site-packages (from requests>=2.27.1->pycaret) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in .\.venv\Lib\site-packages (from requests>=2.27.1->pycaret) (2026.1.4)
Requirement already satisfied: executing>=1.2.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (3.0.1)
Requirement already satisfied: pure-eval in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=5.5.0->pycaret) (0.2.3)

In [4]:
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('None')

In [5]:
from pycaret.classification import *
clf=setup(
       data=df,target='Sleep Disorder',session_id=12
)

In [6]:
best_model = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .           23:08:55
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Compiling Library